# Generated by Django 5.2.10 on 2026-08-14 18:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Lista')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('list_type', models.CharField(choices=[('WHITELIST', 'Whitelist (Permitidos)'), ('BLACKLIST', 'Blacklist (Bloqueados)')], default='WHITELIST', max_length=20)),
                ('color', models.CharField(choices=[('indigo', 'Índigo'), ('emerald', 'Esmeralda / Verde'), ('cyan', 'Ciano / Azul Claro'), ('purple', 'Roxo / Púrpura'), ('amber', 'Âmbar / Laranja'), ('rose', 'Rosa / Vermelho'), ('blue', 'Azul Real')], default='emerald', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lista de Proxy',
                'verbose_name_plural': 'Listas de Proxy',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DomainItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, verbose_name='Domínio')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Observação')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('proxy_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='squid.proxylist')),
            ],
            options={
                'verbose_name': 'Domínio',
                'verbose_name_plural': 'Domínios',
                'ordering': ['domain'],
                'unique_together': {('proxy_list', 'domain')},
            },
        ),
    ]
