# Generated by Django 5.2.10 on 2026-08-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxylist',
            name='is_mandatory',
            field=models.BooleanField(default=False, verbose_name='Obrigatória do Sistema'),
        ),
    ]
