# Generated by Django 5.2.10 on 2026-08-14 19:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_proxyport_current_status'),
        ('squid', '0002_proxylist_is_mandatory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Data / Hora')),
                ('client_ip', models.CharField(max_length=45, verbose_name='IP do Cliente')),
                ('port_number', models.PositiveIntegerField(db_index=True, verbose_name='Porta Proxy')),
                ('method', models.CharField(default='CONNECT', max_length=15, verbose_name='Método')),
                ('domain', models.CharField(db_index=True, max_length=255, verbose_name='Domínio Requisitado')),
                ('full_url', models.CharField(blank=True, max_length=1000, verbose_name='URL Completa')),
                ('http_status', models.CharField(default='TCP_TUNNEL/200', max_length=50, verbose_name='Código / Status Squid')),
                ('action', models.CharField(choices=[('ALLOWED', 'Permitido (Liberado)'), ('BLOCKED', 'Bloqueado (Negado)'), ('DIRECT', 'Acesso Direto')], default='ALLOWED', max_length=20, verbose_name='Ação')),
                ('bytes_sent', models.BigIntegerField(default=0, verbose_name='Bytes Trafegados')),
                ('response_time_ms', models.IntegerField(default=0, verbose_name='Latência (ms)')),
                ('mime_type', models.CharField(default='-', max_length=100, verbose_name='Tipo MIME')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='dashboard.proxygroup')),
                ('port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='dashboard.proxyport')),
            ],
            options={
                'verbose_name': 'Log de Acesso',
                'verbose_name_plural': 'Logs de Acesso',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'port_number'], name='squid_acces_timesta_6bf52d_idx'), models.Index(fields=['domain'], name='squid_acces_domain_fb2671_idx'), models.Index(fields=['action'], name='squid_acces_action_74faad_idx')],
            },
        ),
    ]
