# Generated by Django 5.2.10 on 2026-08-14 19:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squid', '0003_accesslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, unique=True, verbose_name='Endereço IP')),
                ('hostname', models.CharField(max_length=100, verbose_name='Nome / Hostname do Equipamento')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descrição / Localização')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipamento / Hostname',
                'verbose_name_plural': 'Equipamentos / Hostnames',
                'ordering': ['hostname', 'ip_address'],
            },
        ),
    ]
