# Generated by Django 5.2.10 on 2026-08-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_proxyport_current_status'),
        ('squid', '0004_devicehost'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='hostname',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Hostname do Equipamento'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['hostname'], name='squid_acces_hostnam_11b852_idx'),
        ),
    ]
