# Generated by Django 5.2.10 on 2026-08-18 12:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squid', '0005_accesslog_hostname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiddenDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Domínio a Ocultar')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Motivo / Descrição')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Domínio Oculto no Live',
                'verbose_name_plural': 'Domínios Ocultos no Live',
                'ordering': ['domain'],
            },
        ),
    ]
