# Generated by Django 5.2.10 on 2026-08-18 13:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_proxyport_use_custom_portal'),
        ('squid', '0006_hiddendomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título / Nome do Site')),
                ('url', models.URLField(max_length=500, verbose_name='Endereço URL (ex: https://...)')),
                ('category', models.CharField(choices=[('FACULDADES', 'Faculdades & Portais Acadêmicos'), ('PESQUISA', 'Pesquisa & Bibliotecas Virtuais'), ('DICIONARIOS', 'Dicionários & Enciclopédias'), ('FERRAMENTAS', 'Ferramentas & Recursos Educacionais'), ('OUTROS', 'Outros Links Autorizados')], default='FACULDADES', max_length=30, verbose_name='Categoria')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descrição Curta')),
                ('icon', models.CharField(default='fa-graduation-cap', max_length=50, verbose_name='Ícone FontAwesome')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('display_order', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('port', models.ForeignKey(blank=True, help_text='Selecione uma porta específica ou deixe em branco para todas as salas com portal ativo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_links', to='dashboard.proxyport', verbose_name='Porta / Sala Específica')),
            ],
            options={
                'verbose_name': 'Link do Portal',
                'verbose_name_plural': 'Links do Portal',
                'ordering': ['display_order', 'title'],
            },
        ),
    ]
