# Generated by Django 6.1 on 2026-08-18 19:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_roomschedule_action_and_more'),
        ('squid', '0007_portallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedRefererHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome do Portal / Buscador')),
                ('domain_pattern', models.CharField(help_text='Domínio ou regex do site de busca/portal que permite navegar nos resultados', max_length=255, verbose_name='Domínio / Padrão de Origem (ex: scholar.google.com)')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descrição / Finalidade')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ports', models.ManyToManyField(blank=True, help_text='Deixe em branco para aplicar a todas as salas com Whitelist ativa', related_name='allowed_referer_hubs', to='dashboard.proxyport', verbose_name='Salas / Portas Aplicadas')),
            ],
            options={
                'verbose_name': 'Sublinks Liberados (Referer Hub)',
                'verbose_name_plural': 'Sublinks Liberados (Referer Hubs)',
                'ordering': ['name'],
            },
        ),
    ]
