# Generated by Django 6.1 on 2026-08-18 19:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squid', '0008_allowedrefererhub'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveredSublink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Domínio Acessado')),
                ('last_requested_url', models.URLField(blank=True, max_length=500, verbose_name='Última URL Acessada')),
                ('hit_count', models.PositiveIntegerField(default=1, verbose_name='Vezes Acessado')),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Primeiro Acesso')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Último Acesso')),
                ('origin_hub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovered_links', to='squid.allowedrefererhub', verbose_name='Buscador de Origem')),
            ],
            options={
                'verbose_name': 'Sublink Descoberto / Acessado',
                'verbose_name_plural': 'Sublinks Descobertos / Acessados',
                'ordering': ['-last_seen'],
            },
        ),
    ]
