# Generated by Django 5.2.10 on 2026-08-20 18:15

from django.db import migrations

def reorganize_blacklists(apps, schema_editor):
    ProxyList = apps.get_model('squid', 'ProxyList')
    DomainItem = apps.get_model('squid', 'DomainItem')

    list_adtech = ProxyList.objects.filter(slug='publicidade-adtech-rastreadores').first()
    list_social = ProxyList.objects.filter(slug='redes-sociais-mensageiros').first()
    list_streaming = ProxyList.objects.filter(slug='streaming-multimidia').first()

    if not list_social or not list_streaming:
        return

    # Dominios de Redes Sociais permitidos (sem WhatsApp)
    social_domains = {
        '.facebook.com': 'Facebook',
        '.facebook.net': 'Facebook CDNs/SDK',
        '.fbcdn.net': 'Facebook CDNs',
        '.instagram.com': 'Instagram',
        '.tiktok.com': 'TikTok',
        '.kwai.com': 'Kwai',
        '.twitter.com': 'Twitter / X',
        '.x.com': 'X (antigo Twitter)',
        '.t.co': 'X (Link Shortener)',
        '.ads-twitter.com': 'X Ads',
        '.linkedin.com': 'LinkedIn',
        '.licdn.com': 'LinkedIn CDNs',
        '.pinterest.com': 'Pinterest',
        '.telegram.org': 'Telegram',
        '.discord.com': 'Discord',
        '.discord.gg': 'Discord Links',
        '.reddit.com': 'Reddit',
        '.redditstatic.com': 'Reddit CDNs',
        '.snapchat.com': 'Snapchat',
    }

    # Dominios de Streaming permitidos
    streaming_domains = {
        '.youtube.com': 'YouTube',
        '.youtube-nocookie.com': 'YouTube Embedded',
        '.ytimg.com': 'YouTube Assets',
        '.googlevideo.com': 'YouTube Video Delivery',
        '.primevideo.com': 'Amazon Prime Video',
        '.netflix.com': 'Netflix',
        '.hbomax.com': 'HBO Max',
        '.omnycontent.com': 'Podcasts / OmnyStudio',
        '.spotify.com': 'Spotify',
        '.spotifycdn.com': 'Spotify CDNs',
        '.deezer.com': 'Deezer',
        '.twitch.tv': 'Twitch',
        '.vimeo.com': 'Vimeo',
        '.dailymotion.com': 'Dailymotion',
        '.soundcloud.com': 'SoundCloud',
        '.suamusica.com.br': 'Sua Musica',
        '.freemusicas.com': 'Downloads de Musica',
        '.ouvir-musica.com': 'Ouvir Musica',
        '.tokyvideo.com': 'TokyVideo',
        '.bilivideo.com': 'Bilibili Video',
    }

    adtech_move_domains = [
        '.3lift.com', '.a-mx.com', '.adgrx.com', '.adtelligent.com', '.cdnwidget.com',
        '.company-target.com', '.connatix.com', '.deepintent.com', '.lijit.com',
        '.revcontent.com', '.rubiconproject.com', '.sitescout.com', '.stackadapt.com',
        '.tynt.com'
    ]

    # 1. Processar itens de Redes Sociais
    for d in list(list_social.domains.all()):
        domain_name = d.domain
        if domain_name in social_domains:
            d.description = social_domains[domain_name]
            d.save()
        elif domain_name in streaming_domains:
            d.proxy_list = list_streaming
            d.description = streaming_domains[domain_name]
            d.save()
        elif domain_name in adtech_move_domains and list_adtech:
            d.proxy_list = list_adtech
            d.description = "AdTech / Rastreador (Movido de Redes Sociais)"
            d.save()
        else:
            d.delete()

    # Garantir que todos os dominios sociais essenciais existam
    for dom, desc in social_domains.items():
        DomainItem.objects.update_or_create(
            proxy_list=list_social,
            domain=dom,
            defaults={'description': desc}
        )

    # 2. Processar itens de Streaming
    for d in list(list_streaming.domains.all()):
        domain_name = d.domain
        if domain_name in streaming_domains:
            d.description = streaming_domains[domain_name]
            d.save()
        else:
            if domain_name in social_domains:
                d.proxy_list = list_social
                d.description = social_domains[domain_name]
                d.save()
            else:
                d.delete()

    # Garantir que todos os dominios de streaming essenciais existam
    for dom, desc in streaming_domains.items():
        DomainItem.objects.update_or_create(
            proxy_list=list_streaming,
            domain=dom,
            defaults={'description': desc}
        )

class Migration(migrations.Migration):

    dependencies = [
        ('squid', '0009_discoveredsublink'),
    ]

    operations = [
        migrations.RunPython(reorganize_blacklists),
    ]
