# Generated by Django 5.2.10 on 2026-08-20 18:24

from django.db import migrations

def reorganize_remaining_blacklists(apps, schema_editor):
    ProxyList = apps.get_model('squid', 'ProxyList')
    DomainItem = apps.get_model('squid', 'DomainItem')

    # 1. Remover completamente a lista de Publicidade, AdTech & Rastreadores
    list_adtech = ProxyList.objects.filter(slug='publicidade-adtech-rastreadores').first()
    if list_adtech:
        list_adtech.delete()  # Deleta a lista e todos os domínios associados a ela por cascata

    # 2. Definição das outras categorias e seus domínios finais limpos e organizados
    
    # Compras & E-Commerce (slug: compras-e-commerce)
    compras_domains = {
        '.airbnb.com.br': 'Airbnb Brasil (Hospedagem)',
        '.alibaba.com': 'Alibaba (Compras)',
        '.amazon.com': 'Amazon Global',
        '.amazon.com.br': 'Amazon Brasil',
        '.booking.com': 'Booking.com (Viagens)',
        '.media-amazon.com': 'Amazon Imagens e Mídia',
        '.mercadolivre.com': 'Mercado Livre Global',
        '.mercadolivre.com.br': 'Mercado Livre Brasil',
        '.shop.app': 'Shopify Shop App',
        '.shopee.com.br': 'Shopee Brasil',
        '.shopeemobile.com': 'Shopee Assets',
    }

    # Downloads & Compartilhamento (slug: downloads-compartilhamento)
    downloads_domains = {
        '.4shared.com': '4shared (Hospedagem)',
        '.superdownloads.com.br': 'Superdownloads',
        '.wondershare.com': 'Wondershare (Downloads de Softwares)',
        '.mega.nz': 'Mega.nz (Compartilhamento)',
        '.megaupload.com': 'Megaupload',
        '.mediafire.com': 'MediaFire (Hospedagem)',
        '.rapidgator.net': 'Rapidgator',
        '.thepiratebay.org': 'The Pirate Bay (Torrent)',
        '.utorrent.com': 'uTorrent Client',
    }

    # Inteligência Artificial & Bots (slug: inteligencia-artificial-bots)
    ia_domains = {
        '.anthropic.com': 'Claude AI (Anthropic)',
        '.chatgpt.com': 'ChatGPT (OpenAI)',
        '.chatgptbrasil.com.br': 'ChatGPT Brasil',
        '.geminichatgpt.com': 'Gemini / ChatGPT alternativo',
        '.openai.com': 'OpenAI Portal e API',
        '.gemini.google.com': 'Google Gemini AI',
        '.copilot.microsoft.com': 'Microsoft Copilot',
        '.perplexity.ai': 'Perplexity AI',
        '.midjourney.com': 'Midjourney (Geração de Imagens)',
    }

    # Jogos & Apostas (slug: jogos-apostas)
    jogos_domains = {
        '.gameswaka.com': 'Gameswaka',
        '.jogos.com': 'Jogos.com',
        '.bet365.com': 'Bet365 (Apostas)',
        '.sportingbet.com': 'Sportingbet (Apostas)',
        '.blaze.com': 'Blaze Casino / Apostas',
        '.betano.com': 'Betano (Apostas)',
        '.estrela.bet': 'Estrela Bet (Apostas)',
        '.steampowered.com': 'Steam Store',
        '.steamcommunity.com': 'Steam Community',
        '.epicgames.com': 'Epic Games Store',
        '.roblox.com': 'Roblox',
    }

    # Notícias & Portais de Mídia (slug: noticias-portais-de-midia)
    noticias_domains = {
        '.abril.com.br': 'Grupo Abril',
        '.capitalnews.com.br': 'Capital News',
        '.cnnbrasil.com.br': 'CNN Brasil',
        '.estadao.com.br': 'Estadão',
        '.euronews.com': 'Euronews',
        '.globo.com': 'Portal Globo / G1 / GE',
        '.nbcnews.com': 'NBC News',
        '.newsbreak.com': 'Newsbreak',
        '.r7.com': 'Portal R7',
        '.s-nbcnews.com': 'NBC News Assets',
        '.terra.com.br': 'Portal Terra',
        '.uol.com.br': 'Portal UOL',
        '.folha.uol.com.br': 'Folha de S.Paulo',
        '.folha.com.br': 'Folha de S.Paulo (Alternativo)',
        '.metropoles.com': 'Portal Metrópoles',
        '.infomoney.com.br': 'InfoMoney',
        '.jovempan.com.br': 'Portal Jovem Pan',
        '.gazetadopovo.com.br': 'Gazeta do Povo',
    }

    categories_mapping = [
        ('compras-e-commerce', compras_domains),
        ('downloads-compartilhamento', downloads_domains),
        ('inteligencia-artificial-bots', ia_domains),
        ('jogos-apostas', jogos_domains),
        ('noticias-portais-de-midia', noticias_domains)
    ]

    for slug, domain_dict in categories_mapping:
        pl = ProxyList.objects.filter(slug=slug).first()
        if not pl:
            continue

        # Limpar domínios que não pertencem à lista final
        for d in list(pl.domains.all()):
            if d.domain not in domain_dict:
                d.delete()

        # Garantir ou atualizar os domínios finais permitidos na lista
        for dom, desc in domain_dict.items():
            DomainItem.objects.update_or_create(
                proxy_list=pl,
                domain=dom,
                defaults={'description': desc}
            )

class Migration(migrations.Migration):

    dependencies = [
        ('squid', '0010_clean_blacklists'),
    ]

    operations = [
        migrations.RunPython(reorganize_remaining_blacklists),
    ]
