# Generated by Django 5.2.10 on 2026-08-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_roomschedule_action_and_more'),
        ('squid', '0012_add_ai_analysis_to_discovered_sublink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='client_ip',
            field=models.CharField(db_index=True, max_length=45, verbose_name='IP do Cliente'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['client_ip'], name='squid_acces_client__15ec53_idx'),
        ),
    ]
