# Generated by Django 5.2.10 on 2026-08-14 17:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_domainrule_is_verified_alter_domainrule_rule_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('default_policy', models.CharField(choices=[('WHITELIST_STRICT', 'Bloqueio Total (Apenas Whitelist)'), ('SCHEDULED', 'Temporizado / Horários Programados'), ('BLACKLIST_ONLY', 'Liberado Geral com Blacklist')], default='WHITELIST_STRICT', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=60, unique=True)),
                ('value', models.TextField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='domainrule',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='domainrule',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='domainrule',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='domainrule',
            name='rule_type',
            field=models.CharField(choices=[('allow', 'Permitido (Whitelist)'), ('block', 'Bloqueado (Blacklist)'), ('hide', 'Oculto / Ignorado')], default='allow', max_length=10),
        ),
        migrations.AddField(
            model_name='domainrule',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_rules', to='dashboard.proxygroup'),
        ),
        migrations.CreateModel(
            name='ProxyPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_number', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('current_status', models.CharField(choices=[('BLOCKED', 'Bloqueada (Sem Acesso)'), ('WHITELIST', 'Whitelist Básica'), ('ALLOWED', 'Liberada Total (Acesso Completo)'), ('SCHEDULED', 'Agendamento / Horário Automático')], default='WHITELIST', max_length=20)),
                ('temp_allowed_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='dashboard.proxygroup')),
            ],
        ),
        migrations.CreateModel(
            name='RoomSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('days_of_week', models.CharField(default='MTWHF', max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('action', models.CharField(default='ALLOW_ALL', max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='dashboard.proxyport')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador Geral (TI)'), ('MANAGER', 'Coordenador / Gestor de Setor'), ('OPERATOR', 'Operador / Professor')], default='OPERATOR', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_groups', models.ManyToManyField(blank=True, related_name='authorized_users', to='dashboard.proxygroup')),
                ('allowed_ports', models.ManyToManyField(blank=True, related_name='authorized_users', to='dashboard.proxyport')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
