# Generated by Django 5.2.10 on 2026-08-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_proxygroup_systemsetting_and_more'),
        ('squid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxygroup',
            name='blacklists',
            field=models.ManyToManyField(blank=True, related_name='applied_groups_blacklist', to='squid.proxylist'),
        ),
        migrations.AddField(
            model_name='proxygroup',
            name='whitelists',
            field=models.ManyToManyField(blank=True, related_name='applied_groups_whitelist', to='squid.proxylist'),
        ),
    ]
