# Generated by Django 5.2.10 on 2026-08-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_proxygroup_blacklists_proxygroup_whitelists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxyport',
            name='current_status',
            field=models.CharField(choices=[('ALLOWED', 'Liberado Total (100% Livre)'), ('BLACKLIST', 'Liberado com Blacklist'), ('WHITELIST', 'Apenas Whitelist (Padrão Seguro)'), ('SCHEDULED', 'Agendamento / Horário Automático')], default='WHITELIST', max_length=20),
        ),
    ]
