# Generated by Django 5.2.10 on 2026-08-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_proxyport_current_status'),
        ('squid', '0006_hiddendomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxyport',
            name='port_blacklists',
            field=models.ManyToManyField(blank=True, help_text='Blacklists exclusivas desta porta (têm prioridade sobre as listas do grupo)', related_name='applied_ports_blacklist', to='squid.proxylist'),
        ),
        migrations.AddField(
            model_name='proxyport',
            name='port_whitelists',
            field=models.ManyToManyField(blank=True, help_text='Whitelists exclusivas desta porta (têm prioridade sobre as listas do grupo)', related_name='applied_ports_whitelist', to='squid.proxylist'),
        ),
        migrations.AlterField(
            model_name='proxyport',
            name='current_status',
            field=models.CharField(choices=[('ALLOWED', 'Liberado Total (100% Livre)'), ('BLACKLIST', 'Liberado com Blacklist'), ('WHITELIST', 'Apenas Whitelist (Padrão Seguro)'), ('BLOCKED', 'Bloqueio Total (Sem Acesso)'), ('SCHEDULED', 'Agendamento / Horário Automático')], default='WHITELIST', max_length=20),
        ),
    ]
