# Generated by Django 5.2.10 on 2026-08-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_proxyport_blocked_and_port_lists'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxyport',
            name='use_custom_portal',
            field=models.BooleanField(default=False, help_text='Redireciona acessos negados para o portal educacional com lista de links permitidos', verbose_name='Usar Portal de Bloqueio Personalizado'),
        ),
    ]
