# Generated by Django 5.2.10 on 2026-08-18 17:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_proxyport_use_custom_portal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomschedule',
            options={'ordering': ['start_time', 'name'], 'verbose_name': 'Agendamento de Sala', 'verbose_name_plural': 'Agendamentos de Salas'},
        ),
        migrations.AddField(
            model_name='roomschedule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roomschedule',
            name='current_state',
            field=models.CharField(default='INACTIVE', max_length=20, verbose_name='Estado Atual'),
        ),
        migrations.AddField(
            model_name='roomschedule',
            name='last_run_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Execução'),
        ),
        migrations.AddField(
            model_name='roomschedule',
            name='revert_action',
            field=models.CharField(choices=[('ALLOWED', 'Livre (Acesso Total)'), ('WHITELIST', 'Whitelist (Apenas Permitidos)'), ('BLACKLIST', 'Blacklist (Livre com Restrições)'), ('BLOCKED', 'Bloqueado')], default='BLOCKED', max_length=20, verbose_name='Ação Após Término'),
        ),
        migrations.AddField(
            model_name='roomschedule',
            name='schedule_type',
            field=models.CharField(choices=[('RECURRENT', 'Recorrente (Dias da Semana)'), ('ONETIME', 'Pontual (Data Específica)')], default='RECURRENT', max_length=20, verbose_name='Tipo de Agendamento'),
        ),
        migrations.AddField(
            model_name='roomschedule',
            name='specific_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data Específica'),
        ),
        migrations.AddField(
            model_name='roomschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='roomschedule',
            name='action',
            field=models.CharField(choices=[('ALLOWED', 'Livre (Acesso Total)'), ('WHITELIST', 'Whitelist (Apenas Permitidos)'), ('BLACKLIST', 'Blacklist (Livre com Restrições)'), ('BLOCKED', 'Bloqueado')], default='ALLOWED', max_length=20, verbose_name='Ação no Período'),
        ),
        migrations.AlterField(
            model_name='roomschedule',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='roomschedule',
            name='days_of_week',
            field=models.CharField(default='0,1,2,3,4', max_length=50, verbose_name='Dias da Semana'),
        ),
        migrations.AlterField(
            model_name='roomschedule',
            name='end_time',
            field=models.TimeField(verbose_name='Horário de Término'),
        ),
        migrations.AlterField(
            model_name='roomschedule',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='Ativo / Habilitado'),
        ),
        migrations.AlterField(
            model_name='roomschedule',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nome do Agendamento'),
        ),
        migrations.AlterField(
            model_name='roomschedule',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='dashboard.proxyport', verbose_name='Sala / Porta'),
        ),
        migrations.AlterField(
            model_name='roomschedule',
            name='start_time',
            field=models.TimeField(verbose_name='Horário de Início'),
        ),
    ]
