# Generated by Django 5.2.10 on 2026-08-18 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_roomschedule_options_roomschedule_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proxyport',
            name='active_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_on_ports', to='dashboard.roomschedule', verbose_name='Agendamento em Vigor'),
        ),
        migrations.AddField(
            model_name='proxyport',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ports_modified', to=settings.AUTH_USER_MODEL, verbose_name='Último Usuário a Modificar'),
        ),
        migrations.AddField(
            model_name='proxyport',
            name='last_status_source',
            field=models.CharField(default='MANUAL', max_length=50, verbose_name='Origem da Última Alteração'),
        ),
    ]
