# Generated by Django 5.2.10 on 2026-08-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_proxyport_active_schedule_proxyport_last_modified_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomschedule',
            name='action',
            field=models.CharField(choices=[('BLACKLIST', 'Navegação Segura (Blacklist)'), ('WHITELIST', 'Navegação Restrita (Whitelist)'), ('ALLOWED', 'Livre (Acesso Total)'), ('BLOCKED', 'Bloqueado')], default='ALLOWED', max_length=20, verbose_name='Ação no Período'),
        ),
        migrations.AlterField(
            model_name='roomschedule',
            name='revert_action',
            field=models.CharField(choices=[('BLACKLIST', 'Navegação Segura (Blacklist)'), ('WHITELIST', 'Navegação Restrita (Whitelist)'), ('ALLOWED', 'Livre (Acesso Total)'), ('BLOCKED', 'Bloqueado')], default='BLOCKED', max_length=20, verbose_name='Ação Após Término'),
        ),
    ]
